## TLS Connectors
## KB Article https://technet.microsoft.com/library/jj200710(v=exchg.160).aspx
## Does not allow for buildable domains, all domains have to be entered at once


Get-InboundConnector -Identity "Bank of America - Inbound" | Select-Object Name, SenderDomains

Get-OutboundConnector



Set-InboundConnector -Identity "Bank of America - Inbound" -SenderDomains "aviatorschn.com", "bac.com", 	"balboainsurance.com", 	"baml.com", 	"baml2.com", 	"baml3.com", 	"bankofamerica.co.uk", 	"bankofamerica.com", 	"bankofamerica2.com", 	"bankofamerica3.com", 	"basecurities.com", 	"berndale.com.au", 	"bofa.com", 	"bofacapital.com", 	"bofamerch.com", 	"bofasecurities.com", 	"businesscreditcardsonline.co.uk", 	"comm.bankofamerica.com", 	"comm.bankofamerica2.com", 	"comm.bankofamerica3.com", 	"crms.balboainsurance.com", 	"crms.baml.com", 	"crms.bankofamerica.com", 	"crms.landsafe.com", 	"crms.mbna.com", 	"crms.ml.com", 	"crms.recontrustco.com", 	"crms.ustrust.com", 	"dodcommunitybank.com", 	"evalueserve2.com", 	"evergreen.baml.com", 	"evergreen.bankofamerica.com", 	"fiacardservices.com", 	"fxtransact.com", 	"healthlogic.com", 	"hls.ml.com", 	"hlsc.com", 	"innovate.baml.com", 	"innovate.bankofamerica.com", 	"irevna2.com", 	"landsafe.com", 	"landsafecredit.com", 	"leaseadmincenter.com", 	"loans.co.uk", 	"mbna.com", 	"mbnaapply.co.uk", 	"mbnabusinesscardsonline.co.uk", 	"ml.com", 	"mlresearch.ml.com", 	"mortgagesplc.com", 	"mslicenseusa.com", 	"mylearning.balboainsurance.com", 	"mylearning.baml.com", 	"mylearning.bankofamerica.com", 	"mylearning.landsafe.com", 	"mylearning.mbna.com", 	"mylearning.ml.com", 	"mylearning.recontrustco.com", 	"mylearning.ustrust.com", 	"optionnavigator.com", 	"recontrustco.com", 	"ustrust.com", 	"works.com"


Set-OutboundConnector -Identity "Bank of America - Out" -RecipientDomains "aviatorschn.com", 	"bac.com", 	"balboainsurance.com", 	"baml.com", 	"baml2.com", 	"baml3.com", 	"bankofamerica.co.uk", 	"bankofamerica.com", 	"bankofamerica2.com", 	"bankofamerica3.com", 	"basecurities.com", 	"berndale.com.au", 	"bofa.com", 	"bofacapital.com", 	"bofamerch.com", 	"bofasecurities.com", 	"businesscreditcardsonline.co.uk", 	"comm.bankofamerica.com", 	"comm.bankofamerica2.com", 	"comm.bankofamerica3.com", 	"crms.balboainsurance.com", 	"crms.baml.com", 	"crms.bankofamerica.com", 	"crms.landsafe.com", 	"crms.mbna.com", 	"crms.ml.com", 	"crms.recontrustco.com", 	"crms.ustrust.com", 	"dodcommunitybank.com", 	"evalueserve2.com", 	"evergreen.baml.com", 	"evergreen.bankofamerica.com", 	"fiacardservices.com", 	"fxtransact.com", 	"healthlogic.com", 	"hls.ml.com", 	"hlsc.com", 	"innovate.baml.com", 	"innovate.bankofamerica.com", 	"irevna2.com", 	"landsafe.com", 	"landsafecredit.com", 	"leaseadmincenter.com", 	"loans.co.uk", 	"mbna.com", 	"mbnaapply.co.uk", 	"mbnabusinesscardsonline.co.uk", 	"ml.com", 	"mlresearch.ml.com", 	"mortgagesplc.com", 	"mslicenseusa.com", 	"mylearning.balboainsurance.com", 	"mylearning.baml.com", 	"mylearning.bankofamerica.com", 	"mylearning.landsafe.com", 	"mylearning.mbna.com", 	"mylearning.ml.com", 	"mylearning.recontrustco.com", 	"mylearning.ustrust.com", 	"optionnavigator.com", 	"recontrustco.com", 	"ustrust.com", 	"works.com"
